#!/bin/sh
sudo curl -L -o /etc/apt/sources.list.d/winehq.list https://github.com/chrissxYT/winstallhq/raw/master/winehq.list
curl -L https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 76F1A20FF987672F
sudo apt update
sudo apt install wine-staging
