#!/bin/sh
sudo add-apt-repository \
        "deb https://dl.winehq.org/wine-builds/debian/ buster main"
curl -L https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 76F1A20FF987672F
sudo apt update
sudo apt install -y wine-staging
